# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroInv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
